export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "category/FECT_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "category/FECT_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "category/FECT_CATEGORIES_FAILED",
};
